/* Content data: solutions, case studies, industries.
   Edit here to add or change catalog entries; pages render from this. */
window.DATA = {
  /* Small inline icons for workflow nodes. Keyed by name. */
  icons: {
    lead:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 4-6 8-6s8 2 8 6"/></svg>',
    web:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18"/></svg>',
    ai:    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3l2 5 5 2-5 2-2 5-2-5-5-2 5-2z"/></svg>',
    crm:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M9 21V9"/></svg>',
    msg:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 5h16v11H8l-4 4z"/></svg>',
    cal:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M3 10h18M8 3v4M16 3v4"/></svg>',
    bell:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 16V11a6 6 0 0112 0v5l2 2H4zM10 20a2 2 0 004 0"/></svg>',
    star:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3l2.8 5.7 6.2.9-4.5 4.4 1 6.2L12 17.3 6.5 20.2l1-6.2L3 9.6l6.2-.9z"/></svg>',
    check: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 12l5 5L20 6"/></svg>',
    doc:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4M9 12h6M9 16h6"/></svg>',
    card:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="6" width="18" height="12" rx="2"/><path d="M3 10h18"/></svg>',
    chart: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>',
    box:   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 7l9-4 9 4v10l-9 4-9-4z"/><path d="M3 7l9 4 9-4M12 11v10"/></svg>',
    team:  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="8" cy="8" r="3"/><circle cx="16" cy="9" r="3"/><path d="M2 20c0-3 3-5 6-5s6 2 6 5M12 20c0-3 2-5 5-5s5 2 5 5"/></svg>',
  },

  /* Hero flow (home) */
  heroFlow: [
    ["lead", "Lead", "website form · 21:14"],
    ["web", "AI website", "answers, captures details"],
    ["ai", "Qualification", "service, urgency, budget"],
    ["crm", "CRM", "contact created, tagged"],
    ["msg", "WhatsApp / Email", "reply in seconds"],
    ["cal", "Appointment", "slot booked to your calendar"],
    ["bell", "Follow-up", "reminder, review request"],
  ],

  solutions: [
    {
      id: "ai-booking", badge: "Target · 20–30% fewer no-shows", cat: "Appointment booking", name: "AI Booking Website",
      industry: ["healthcare", "fitness", "professional", "education", "other"], uses: ["booking", "leads", "followup"],
      size: "tall",
      outcome: "For clinics, salons, consultants and appointment-based businesses.",
      tagline: "Turn website visitors into qualified appointments without your team managing every conversation.",
      flow: [["lead","Visitor"],["web","AI website"],["ai","Qualification"],["cal","Calendar"],["check","Confirmation"],["bell","Reminder"],["star","Follow-up"]],
      problem: "Appointment-based businesses lose bookings in the gap between a visitor's interest and a human reply. Calls go unanswered during treatments or sessions, evening enquiries wait until morning, and nobody reminds the people who did book. The result is empty slots and a reception desk that spends its day on the phone.",
      included: [
        ["AI website", "A fast site that answers questions from your own material and steers visitors to book."],
        ["Qualification", "Collects service, urgency and preferences before offering a slot."],
        ["Calendar sync", "Real availability per practitioner, room or trainer. No double bookings."],
        ["Confirmations and reminders", "Email and WhatsApp, with one-tap rescheduling."],
        ["CRM record", "Every booking creates or updates a contact you own."],
        ["Review request", "Sent after the visit, routed to Google or your platform of choice."],
      ],
      how: [
        ["A visitor asks a question or clicks Book", "The AI answers from your FAQ, pricing and policies. It never invents an answer it does not have."],
        ["Details are collected", "Service, preferred time, contact and anything you need to prepare."],
        ["A slot is offered from your live calendar", "The visitor picks one. The event lands on the right calendar with the collected details."],
        ["Confirmation and reminders go out", "24 hours and 2 hours before, with a reschedule link. Cancellations free the slot automatically."],
        ["After the visit", "A review request, and a follow-up if they need to rebook."],
      ],
      impact: [["24/7", "Lead response availability"], ["One workflow", "From visitor to appointment"], ["Fewer no-shows", "Reminders and easy rescheduling"]],
      stack: ["Cal.com", "WhatsApp Business", "Google Calendar", "CRM or Sheets"],
      setup: "3–4 weeks", bestFor: "Clinics, salons, consultants",
    },
    {
      id: "lead-followup", badge: "Target · reply in seconds, 24/7", cat: "Lead generation", name: "Lead Capture + Follow-Up",
      industry: ["fitness", "home", "professional", "education", "other"], uses: ["leads", "followup", "sales", "crm"],
      size: "wide",
      outcome: "Capture, qualify and automatically follow up with new prospects.",
      tagline: "Every enquiry gets an instant reply and a follow-up sequence that stops the moment they answer.",
      flow: [["lead","New lead"],["ai","AI qualifies"],["crm","CRM updated"],["msg","WhatsApp message"],["cal","Appointment booked"],["team","Team notified"]],
      problem: "Leads arrive from forms, ads, DMs and missed calls, then sit until someone has time. Follow-ups depend on memory. The prospects who go quiet are never nudged, and the ones who are ready get the same slow reply as everyone else.",
      included: [
        ["Capture from every channel", "Website forms, ad forms, WhatsApp, missed calls."],
        ["Instant qualification", "The AI asks the two or three questions you would ask first."],
        ["CRM routing", "Contact created, tagged, assigned to the right person."],
        ["Follow-up sequence", "Reply, nudge, offer, over the channels the lead used."],
        ["Booking hand-off", "Ready leads are offered a call or visit slot."],
        ["Team alerts", "Hot leads notified to the owner or sales person immediately."],
      ],
      how: [
        ["A lead comes in from any channel", "Form, ad, DM or missed call. All land in one flow."],
        ["The AI replies within seconds and qualifies", "Service, timing, budget. Answers are logged to the CRM."],
        ["Routing and alerts", "Qualified leads go to the right person with a summary. Unqualified ones get a polite redirect."],
        ["Follow-ups run on a schedule", "Day 1, day 3, day 7, in your voice. They stop as soon as the lead replies or books."],
      ],
      impact: [["Seconds", "Time to first reply, any hour"], ["Zero", "Leads forgotten in a spreadsheet"], ["Fewer manual tasks", "Follow-ups run themselves"]],
      stack: ["n8n", "CRM", "WhatsApp Business", "Email"],
      setup: "2–3 weeks", bestFor: "Gyms, trades, agencies",
    },
    {
      id: "ai-support", badge: "Target · most tickets without a human", cat: "Customer support", name: "AI Customer Support",
      industry: ["ecommerce", "professional", "healthcare", "other"], uses: ["support", "followup"],
      outcome: "Answer common questions 24/7 and route complex requests to your team.",
      tagline: "Handle the questions you answer every day automatically, and hand the rest to a human with full context.",
      flow: [["msg","Question"],["ai","AI answers"],["team","Escalate if needed"],["check","Resolved"]],
      problem: "Most support messages ask the same twenty things. Answering them by hand costs hours a day and still leaves customers waiting. The genuinely complex requests get buried in the queue.",
      included: [
        ["Knowledge from your material", "Trained on your FAQs, policies and documents. Updated when you update them."],
        ["Web chat, WhatsApp and email", "The same assistant on every channel."],
        ["Human hand-off", "Escalates with the full conversation and customer record attached."],
        ["Conversation log", "Every exchange searchable in one place."],
        ["Gap report", "Weekly list of questions it could not answer, so you can fill the gaps."],
      ],
      how: [
        ["A customer asks on any channel", "Web chat, WhatsApp or email."],
        ["The assistant answers from your knowledge", "If confidence is low, it says so and offers a human."],
        ["Escalation with context", "Your team receives the transcript and the customer record, not a cold ticket."],
        ["The knowledge base improves", "Unanswered questions are reviewed weekly and added."],
      ],
      impact: [["24/7", "Answers without waiting"], ["Most tickets", "Handled without a human"], ["Full context", "On every escalation"]],
      stack: ["Web chat", "WhatsApp Business", "Helpdesk", "LLM provider"],
      setup: "2–4 weeks", bestFor: "Stores, service firms, clinics",
    },
    {
      id: "whatsapp", badge: "Target · every chat logged, none lost", cat: "Messaging", name: "WhatsApp Automation",
      industry: ["healthcare", "fitness", "home", "ecommerce", "education", "other"], uses: ["leads", "followup", "support", "booking"],
      outcome: "Turn WhatsApp conversations into structured business workflows.",
      tagline: "Bookings, confirmations, updates and follow-ups on the channel your customers already use.",
      flow: [["msg","Message in"],["ai","Intent detected"],["cal","Action taken"],["check","Confirmed on WhatsApp"]],
      problem: "WhatsApp is where customers want to talk, but it lives on one phone, nothing is logged, and every message needs a human. Bookings, payments and updates get lost between chats.",
      included: [
        ["Official WhatsApp Business API", "Verified number, templates approved, no grey-market tools."],
        ["Intent handling", "Book, reschedule, ask, pay, complain. Each routed to the right flow."],
        ["Two-way sync", "Calendar, CRM and orders update from the chat, and the chat updates from them."],
        ["Broadcast with rules", "Reminders and updates only to the people who should get them."],
      ],
      how: [
        ["A customer messages your business number", "Any time of day."],
        ["The assistant works out what they need", "And either handles it or asks one clarifying question."],
        ["The action is taken in your systems", "Booking created, order looked up, payment link sent."],
        ["The customer gets a confirmation", "And your team sees the full thread in the CRM."],
      ],
      impact: [["One number", "Shared, logged, never lost"], ["Seconds", "Reply time on WhatsApp"], ["Structured", "Chats become records"]],
      stack: ["WhatsApp Business API", "n8n", "CRM", "Cal.com"],
      setup: "2–4 weeks", bestFor: "Any business that lives on WhatsApp",
    },
    {
      id: "crm", badge: "Target · zero forgotten follow-ups", cat: "CRM", name: "CRM Automation",
      industry: ["professional", "home", "fitness", "other"], uses: ["crm", "sales", "ops", "followup"],
      outcome: "Automatically organize leads, customers and follow-ups.",
      tagline: "A CRM that fills itself in, so your team looks at it instead of typing into it.",
      flow: [["lead","Contact event"],["crm","Record updated"],["ai","Next step decided"],["bell","Task or message"]],
      problem: "A CRM only works if people update it, and nobody has time. Records go stale, follow-ups are missed, and the pipeline report is fiction.",
      included: [
        ["Automatic records", "Every form, booking, call and message creates or updates the contact."],
        ["Stage rules", "Deals move when real events happen, not when someone remembers."],
        ["Task generation", "Follow-up tasks created and assigned with due dates."],
        ["Data hygiene", "Duplicates merged, fields normalised, dead leads archived."],
        ["Owner dashboard", "Pipeline and activity pulled live, not compiled by hand."],
      ],
      how: [
        ["Connect the sources", "Website, calendar, messaging, invoicing."],
        ["Define the stages and rules", "Together, in plain language. We implement them."],
        ["Records update on events", "New booking moves the deal. Paid invoice closes it."],
        ["People get tasks, not admin", "Only the follow-ups that need a human land on a to-do list."],
      ],
      impact: [["Live", "Pipeline you can trust"], ["Fewer manual tasks", "Data entry removed"], ["Zero", "Forgotten follow-ups"]],
      stack: ["HubSpot, Pipedrive or Sheets", "n8n", "Email"],
      setup: "2–3 weeks", bestFor: "Agencies, trades, consultants",
    },
    {
      id: "reviews", badge: "Target · every customer asked", cat: "Reviews", name: "Review Automation",
      industry: ["healthcare", "fitness", "home", "ecommerce", "education", "other"], uses: ["reviews", "followup"],
      outcome: "Automatically request reviews after completed services.",
      tagline: "Ask every happy customer at the right moment, and hear about the unhappy ones privately first.",
      flow: [["check","Service completed"],["msg","Request sent"],["star","Review posted"],["chart","Tracked"]],
      problem: "Reviews drive local search and trust, but asking is awkward and easily forgotten. The businesses that get reviews are the ones that ask every time.",
      included: [
        ["Trigger on completion", "Appointment done, order delivered, invoice paid."],
        ["Timed request", "Sent when the experience is fresh, on the customer's channel."],
        ["Private feedback first", "Unhappy customers are routed to you, not to a public page."],
        ["Reminder", "One polite nudge if no response."],
        ["Tracking", "Review count and rating pulled into your dashboard."],
      ],
      how: [
        ["A service is marked complete", "In your calendar, store or invoicing tool."],
        ["The request goes out", "A short message with a direct link to leave a review."],
        ["Sentiment check", "A quick thumbs up or down. Down goes to you privately."],
        ["Follow-up and tracking", "One reminder, and the numbers on your dashboard."],
      ],
      impact: [["Every customer", "Asked, every time"], ["Private first", "Problems reach you, not Google"], ["Steady", "Flow of new reviews"]],
      stack: ["Google Business Profile", "WhatsApp or Email", "n8n"],
      setup: "1–2 weeks", bestFor: "Any business with repeat customers",
    },
    {
      id: "ecommerce-support", badge: "Target · 60%+ tickets self-served", cat: "E-commerce", name: "E-commerce AI Support",
      industry: ["ecommerce"], uses: ["support", "ops", "followup"],
      outcome: "Answer product questions, assist customers and automate order communication.",
      tagline: "An assistant that reads live order data, so \"where is my order\" is answered before anyone asks.",
      flow: [["msg","Customer asks"],["box","Order lookup"],["ai","Answer"],["team","Escalate if needed"],["star","Review ask"]],
      problem: "Most store support tickets are status questions. Answering them means looking up orders by hand, and pre-sale product questions wait behind the queue until the buyer is gone.",
      included: [
        ["Live order lookup", "By email or order number, with tracking link."],
        ["Product knowledge", "Answers from your catalogue, sizing and policies."],
        ["Proactive updates", "Shipped, delayed, delivered, on email and WhatsApp."],
        ["Escalation", "Complex cases to your team with order and conversation attached."],
        ["Post-delivery flow", "Review request and reorder nudge."],
      ],
      how: [
        ["Connect the store", "Shopify, WooCommerce or a custom platform."],
        ["The assistant goes live on chat, WhatsApp and email", "Trained on your catalogue and policies."],
        ["Status questions answer themselves", "And proactive updates reduce how many are asked at all."],
        ["The team handles only exceptions", "Refund disputes, damaged goods, special requests."],
      ],
      impact: [["Most tickets", "Resolved without a human"], ["Seconds", "Pre-sale answers, 24/7"], ["Fewer manual tasks", "Status updates automated"]],
      stack: ["Shopify or WooCommerce", "Helpdesk", "WhatsApp Business", "Email"],
      setup: "3–4 weeks", bestFor: "Shopify and WooCommerce stores",
    },
    {
      id: "internal-ops", badge: "Target · hours a week given back", cat: "Internal operations", name: "Internal Operations",
      industry: ["professional", "home", "healthcare", "education", "ecommerce", "other"], uses: ["ops", "crm"],
      outcome: "Automate repetitive administrative workflows.",
      tagline: "The daily chores that keep a business running, done by software: reports, documents, notifications, syncs.",
      flow: [["doc","Event in tool A"],["ai","Transform"],["crm","Update tool B"],["bell","Notify"],["chart","Daily report"]],
      problem: "Small teams lose hours a week to copying data between tools, generating the same documents and compiling the same reports. It is invisible work until you add it up.",
      included: [
        ["Tool-to-tool sync", "Forms to sheets, bookings to invoices, payments to accounting."],
        ["Document generation", "Quotes, invoices, contracts, from templates and live data."],
        ["Notifications", "Staff told what changed, where, and what to do."],
        ["Daily and weekly reports", "Enquiries, bookings, payments, in one message to the owner."],
        ["Monitoring", "Every automation logged and alerting on failure."],
      ],
      how: [
        ["We list the recurring chores", "With you, in one session. Usually 10 to 20 of them."],
        ["We rank by hours saved and risk", "And build the top few first."],
        ["Each automation is tested on real data", "Then switched on with monitoring."],
        ["We add the next ones monthly", "As the first batch proves itself."],
      ],
      impact: [["Hours a week", "Given back to the team"], ["One report", "Accurate picture of the business"], ["Logged", "Every automation, every run"]],
      stack: ["n8n", "Google Workspace", "Accounting tool", "Slack or WhatsApp"],
      setup: "3–5 weeks", bestFor: "Small teams with many tools",
    },
  ],

  cases: [
    {
      id: "dental-uk", title: "Dental practice", industry: "Healthcare", country: "United Kingdom", status: "Illustrative scenario",
      duration: "4 weeks", clientType: "Two-dentist practice", solutions: ["ai-booking", "reviews"],
      ifYou: "If your front desk is drowning in calls and messages, this is for you.",
      problem: "Leads were arriving outside business hours and follow-up was inconsistent.",
      built: "AI website + lead qualification + automated booking + reminders.",
      results: [["Faster", "lead response, day and night"], ["Hours a week", "of admin removed from reception"]],
      challenge: "The practice had one receptionist covering phone, front desk and billing. Calls that came during treatments went to voicemail, and evening website enquiries were answered the next morning, by which time many patients had booked elsewhere. There were no reminders, so a few appointments a day simply did not happen. WhatsApp messages from patients accumulated on the principal dentist's personal phone.",
      before: ["Patient calls → voicemail → callback next morning", "Website form → email inbox → replied when quiet", "No reminders → daily no-shows", "WhatsApp on a personal phone, nothing logged"],
      after: ["AI website answers hours, prices and prep questions instantly", "Qualification collects treatment and urgency, then offers real slots", "Booking lands on the right dentist's calendar with the details", "Reminders at 24 h and 2 h with a reschedule link", "Missed call → automatic text with the booking link", "Review request 2 hours after each completed visit"],
      flow: [["lead","Enquiry, any hour"],["web","AI website answers"],["ai","Treatment + urgency"],["cal","Slot booked"],["bell","Reminders"],["check","Visit"],["star","Review request"]],
      metrics: [["35%", "faster lead response", "Target range for this scenario"], ["12 hrs", "per week of admin removed", "Estimated from reception time log"], ["20–30%", "fewer no-shows", "Typical for reminder + reschedule flows"]],
      takeaway: "Reception was never the problem. The gap between a patient's interest and a human reply was. Closing that gap with instant answers and real-time booking did more than any extra staff member could.",
    },
    {
      id: "plumbing-au", title: "Plumbing company", industry: "Home services", country: "Australia", status: "Illustrative scenario",
      duration: "3 weeks", clientType: "Owner plus three engineers", solutions: ["lead-followup", "internal-ops"],
      ifYou: "If you write quotes at night and chase invoices by phone, this is for you.",
      problem: "Quotes took one to two days to send, and jobs went to whoever replied first.",
      built: "Photo intake + AI quote draft + job scheduling + invoicing + review request.",
      results: [["Under an hour", "from enquiry to quote sent"], ["Same day", "invoices, every time"]],
      challenge: "Customers texted photos of the problem during the day. The owner wrote quotes at the kitchen table at night, usually a day or two later. Job details lived in the owner's head, invoices went out late and chasing payment was uncomfortable. Every hour on admin was an hour not on site.",
      before: ["Photos by text → quote written at night → sent 1–2 days later", "Job details in the owner's head", "Invoice sent when remembered", "Payment chased by phone"],
      after: ["Intake form on site and WhatsApp: photos, postcode, description, urgency", "AI drafts a quote from the price list; owner approves from their phone", "Accepted quote creates the job and offers slots from the shared calendar", "Job done → invoice generated and sent → reminders at 7 and 14 days", "Review request after payment clears"],
      flow: [["lead","Photos + description"],["ai","Quote drafted"],["check","Owner approves"],["cal","Job booked"],["doc","Invoice sent"],["card","Paid"],["star","Review request"]],
      metrics: [["< 1 hr", "enquiry to quote", "Target for this workflow"], ["10+ hrs", "per week of owner admin removed", "Estimated from two-week time log"], ["Same day", "invoice sent, every job", "Automated on job completion"]],
      takeaway: "The business did not need more leads. It needed to answer the leads it had before a competitor did, and to stop doing paperwork at midnight.",
    },
    {
      id: "store-ae", title: "Online homeware store", industry: "E-commerce", country: "United Arab Emirates", status: "Illustrative scenario",
      duration: "3 weeks", clientType: "Two-person team, Shopify", solutions: ["ecommerce-support", "reviews"],
      ifYou: "If most of your support inbox asks where an order is, this is for you.",
      problem: "The support inbox was mostly order-status questions, answered by hand a day later.",
      built: "AI support with live order lookup + proactive shipping updates + escalation + review flow.",
      results: [["Most tickets", "resolved without a human"], ["Seconds", "pre-sale answers, 24/7"]],
      challenge: "The majority of support emails asked where an order was. The team looked each one up manually and replied within a day. Product questions from potential buyers queued behind the status questions and were often answered after the buyer had moved on.",
      before: ["\"Where is my order?\" → manual lookup → reply next day", "Product question → waits behind the queue → buyer gone", "No proactive updates, so every delay produced a ticket"],
      after: ["Assistant on chat, WhatsApp and email trained on catalogue and policies", "Live order lookup with tracking link", "Shipped, delayed and delivered notifications sent automatically", "Escalation to the team with order and conversation attached", "Review and reorder nudge a week after delivery"],
      flow: [["msg","Customer asks"],["box","Order lookup"],["ai","Answer in seconds"],["team","Escalate if needed"],["bell","Proactive updates"],["star","Review request"]],
      metrics: [["60%+", "tickets resolved without a human", "Target range for this scenario"], ["< 1 hr", "team support time per day", "Down from most of the morning"], ["24/7", "pre-sale answers", "Assistant availability"]],
      takeaway: "The cheapest ticket is the one that is never opened. Telling customers where their order is before they ask removed most of the queue.",
    },
  ],

  industries: [
    { id: "healthcare", name: "Healthcare", who: "Clinics, dental practices, physios, diagnostics", pain: "Calls missed during treatments, no reminders, evening enquiries answered next morning.", hero: "Built for clinics, dentists and care providers who need more booked appointments and fewer missed calls.", sols: ["ai-booking", "whatsapp", "reviews"] },
    { id: "fitness", name: "Fitness", who: "Gyms, studios, personal trainers", pain: "DMs and trial requests answered late, trials that never convert.", hero: "Built for gyms, studios and trainers who want trial requests answered fast and turned into members.", sols: ["lead-followup", "ai-booking", "whatsapp"] },
    { id: "beauty", name: "Salons and beauty", who: "Salons, spas, aesthetics", pain: "Phone tag for bookings, last-minute cancellations, no waitlist.", hero: "Built for salons, spas and aesthetics clinics that want bookings without phone tag.", sols: ["ai-booking", "whatsapp", "reviews"] },
    { id: "home", name: "Home services", who: "Plumbers, electricians, cleaners, landscapers", pain: "Quotes written at night, jobs lost to faster replies, invoices late.", hero: "Built for plumbers, electricians and cleaners who want quotes out fast and invoices paid on time.", sols: ["lead-followup", "internal-ops", "reviews"] },
    { id: "ecommerce", name: "E-commerce", who: "Shopify, WooCommerce and custom stores", pain: "Support inbox full of status questions, pre-sale questions unanswered.", hero: "Built for online stores that want status questions answered before they land in the inbox.", sols: ["ecommerce-support", "whatsapp", "reviews"] },
    { id: "professional", name: "Professional services", who: "Accountants, lawyers, consultants, agencies", pain: "Unqualified calls on the calendar, proposals never chased, CRM out of date.", hero: "Built for accountants, lawyers, consultants and agencies who want qualified calls and a CRM that stays current.", sols: ["lead-followup", "crm", "ai-booking"] },
    { id: "education", name: "Education", who: "Tutors, coaching centres, small academies", pain: "Trial classes missed, parents not updated, fees chased by hand.", hero: "Built for tutors, coaching centres and academies that want trial classes booked and parents kept in the loop.", sols: ["ai-booking", "whatsapp", "internal-ops"] },
    { id: "local", name: "Local services", who: "Restaurants, repair shops, pet care, any local business", pain: "Missed calls, repetitive questions, no follow-up after the visit.", hero: "Built for restaurants, repair shops and local businesses that miss calls and want customers to come back.", sols: ["whatsapp", "ai-support", "reviews"] },
  ],

  useLabels: { leads: "Lead generation", booking: "Appointment booking", support: "Customer support", followup: "Follow-up", ops: "Internal operations", reviews: "Reviews", sales: "Sales", crm: "CRM" },
  industryLabels: { healthcare: "Healthcare", fitness: "Fitness", home: "Home services", ecommerce: "E-commerce", professional: "Professional services", education: "Education", other: "Other" },
};
